---
title: "R Training Information"
format: html
---

Welcome to the new edition of *Introduction to R for Data Analysis* Training!
This page contains all the essential details for the training.
Please bookmark this page for quick access.

## Calendar

- Starts from: 2nd October 2026  
- Time slots: **9:30 am – 12:30 pm**
- Format: online via [Visio](https://lasuite.numerique.gouv.fr/produits/visio) (link will be shared with registered participants)
- Provisional schedule:  

| **Session**        | **Topic**                           | **Planned Date** |
|------------------------|----------------------------------------------| ---------|
|  1    | Kickstart with R: Your Gateway to Data Science                |  02/10/2026 |
|  2    | Data Foundations: Vectors and Matrices                        |  09/10/2026 |
|  3    | More Complex Data Structures: Data Frames and Lists           |  16/10/2026 |
| \-\-\-    |   Break |  \-\-\-     |
|  4    | Building Logic: Operators, Conditions and Functions           |  06/11/2026 |
|  5    | Graphing with {`ggplot2`}  (Part 1)                           |  13/11/2026 |
| \-\-\-    |  Break |  \-\-\-     |
|  6    | R-fresh: Revisiting the Essentials                            |  27/11/2026 |
|  7    | Tidy Up: Wrangling Data with {`dplyr`} and {`tidyr`} |  04/12/2026 |
|  8    | Graphs Level Up: {`ggplot2`} (Part 2) & Custom Functions      |  11/12/2026 |
|  9    | Putting It All Together: Reproducible Analysis with Quarto |  18/12/2026 |
|  10   | Your project presentation                                     |  TBD     |


## Recommended Readings

- [R for Data Science](https://r4ds.hadley.nz) by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund.
- [Hands-On Programming with R](https://rstudio-education.github.io/hopr/) by Garrett Grolemund 
- [ggplot2: Elegant Graphics for Data Analysis](https://ggplot2.tidyverse.org) by Hadley Wickham 
- [YaRrr! The Pirate’s Guide to R](https://bookdown.org/ndphillips/YaRrr/) by Nathaniel D. Phillips
- [CRAN R Documentation](https://cran.r-project.org/)
